spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgresdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
outputdir: ${OUTPUT_DIR:./output}